name: spacenetic_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_ui_auth: ^1.2.4
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_signin_button: ^2.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^5.4.4
  http: ^0.13.5
  lottie: ^2.3.2
  flutterfire_ui: ^0.4.3+20
  cloud_firestore: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
