// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDe-pZThuceZ96DG6vwFDofyku9kEi78',
    appId: '1:1092881218475:web:75a281ed3a670f144770ee',
    messagingSenderId: '1092881218475',
    projectId: 'spacenetic-9a16d',
    authDomain: 'spacenetic-9a16d.firebaseapp.com',
    storageBucket: 'spacenetic-9a16d.appspot.com',
    measurementId: 'G-EFZWZ62K1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBavSG9uocAMzsEQTSD4IUJihwS8nMYDOY',
    appId: '1:1092881218475:android:b3d85756568e3d9a4770ee',
    messagingSenderId: '1092881218475',
    projectId: 'spacenetic-9a16d',
    storageBucket: 'spacenetic-9a16d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHPGj7TjtpU_9nXTiTa5Og6iBab35-8tA',
    appId: '1:1092881218475:ios:500b1e1eb0d9a8a04770ee',
    messagingSenderId: '1092881218475',
    projectId: 'spacenetic-9a16d',
    storageBucket: 'spacenetic-9a16d.appspot.com',
    iosClientId: '1092881218475-lgrhat555702aiiap93mteblf6jqk55u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceneticFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHPGj7TjtpU_9nXTiTa5Og6iBab35-8tA',
    appId: '1:1092881218475:ios:500b1e1eb0d9a8a04770ee',
    messagingSenderId: '1092881218475',
    projectId: 'spacenetic-9a16d',
    storageBucket: 'spacenetic-9a16d.appspot.com',
    iosClientId: '1092881218475-lgrhat555702aiiap93mteblf6jqk55u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spaceneticFlutter',
  );
}
